version: '3.7'
services:
    db:
        build: ./docker/mysql
        command: ['--default-authentication-plugin=mysql_native_password']
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysqlvolume:/var/lib/mysql
    php:
        build: ./docker/php-fpm
        env_file:
            - ./docker/php-fpm/php.env
        ports:
            - '9001:9001'
        volumes:
            - ${SYMFONY_FOLDER}:/var/www/symfony:cached
        links:
            - db
    nginx:
        build: ./docker/nginx
        ports:
            - '80:80'
        links:
            - php
        volumes:
            - ./app:/var/www/symfony:cached

volumes:
    mysqlvolume:
